AWSTemplateFormatVersion: '2010-09-09'
Description: DevOps Assignment - EC2 Infrastructure Setup

Resources:

  DevOpsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  DevOpsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0fe8bec493a81c7da
      KeyName: devops-key
      SecurityGroups:
        - !Ref DevOpsSecurityGroup
      Tags:
        - Key: Name
          Value: DevOpsServer
