AWSTemplateFormatVersion: '2010-09-09'
Description: DevOps Assignment - EC2 Infrastructure Setup (Region-safe AMI)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access

Mappings:
  AWSRegionToAMI:
    eu-west-1:   # Ireland
      AMI: ami-0a422d70f727fe93e
    eu-central-1: # Frankfurt (optional)
      AMI: ami-0c1c30571d2dae5c9
    us-east-1:   # N. Virginia (optional)
      AMI: ami-0c02fb55956c7d316

Resources:
  DevOpsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  DevOpsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [AWSRegionToAMI, !Ref "AWS::Region", AMI]
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref DevOpsSecurityGroup
      Tags:
        - Key: Name
          Value: DevOpsServer

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref DevOpsInstance
  PublicIP:
    Description: Public IP of the instance
    Value: !GetAtt DevOpsInstance.PublicIp
